[package]
name = "rs-pdf"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-multipart = "0.7.2"
actix-web = "4.9.0"
flate2 = "1.0.34"
lopdf = "=0.34.0"
serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0.132"
